export const category = [
  {text: 'TV Shows', slug: 'tv-shows'},
  {text: 'Phim Lẻ', slug: 'phim-le'},
  {text: 'Phim Bộ', slug: 'phim-bo'},
  {text: 'Phim Đang Chiếu', slug: 'phim-dang-chieu'},
  {text: 'Hành Động', slug: 'hanh-dong'},
  {text: 'Phiêu Lưu', slug: 'phieu-luu'},
  {text: 'Hoạt Hình', slug: 'hoat-hinh'},
  {text: 'Phim Hài', slug: 'phim-hai'},
  {text: 'Hình Sự', slug: 'hinh-su'},
  {text: 'Tài Liệu', slug: 'tai-lieu'},
  {text: 'Chính Kịch', slug: 'chinh-kich'},
  {text: 'Gia Đình', slug: 'gia-dinh'},
  {text: 'Giả Tưởng', slug: 'gia-tuong'},
  {text: 'Lịch Sử', slug: 'lich-su'},
  {text: 'Kinh Dị', slug: 'kinh-di'},
  {text: 'Nhạc', slug: 'phim-nhac'},
  {text: 'Bí Ẩn', slug: 'bi-an'},
  {text: 'Lãng Mạn', slug: 'lang-man'},
  {text: 'Khoa Học Viễn Tưởng', slug: 'khoa-hoc-vien-tuong'},
  {text: 'Gây Cấn', slug: 'gay-can'},
  {text: 'Chiến Tranh', slug: 'chien-tranh'},
  {text: 'Tâm Lý', slug: 'tam-ly'},
  {text: 'Tình Cảm', slug: 'tinh-cam'},
  {text: 'Cổ Trang', slug: 'co-trang'},
  {text: 'Miền Tây', slug: 'mien-tay'},
  {text: 'Phim 18+', slug: 'phim-18'},
];

export const countries = [
  {text: 'Âu Mỹ', slug: 'au-my'},
  {text: 'Anh', slug: 'anh'},
  {text: 'Trung Quốc', slug: 'trung-quoc'},
  {text: 'Indonesia', slug: 'indonesia'},
  {text: 'Việt Nam', slug: 'viet-nam'},
  {text: 'Pháp', slug: 'phap'},
  {text: 'Hồng Kông', slug: 'hong-kong'},
  {text: 'Hàn Quốc', slug: 'han-quoc'},
  {text: 'Nhật Bản', slug: 'nhat-ban'},
  {text: 'Thái Lan', slug: 'thai-lan'},
  {text: 'Đài Loan', slug: 'dai-loan'},
  {text: 'Nga', slug: 'nga'},
  {text: 'Hà Lan', slug: 'ha-lan'},
  {text: 'Philippines', slug: 'philippines'},
  {text: 'Ấn Độ', slug: 'an-do'},
  {text: 'Quốc gia khác', slug: 'quoc-gia-khac'},
];

export const years = [
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2022',
  '2023',
  '2024',
];
