export const category = [
  {text: 'TV Shows', slug: 'tv-shows'},
  {text: 'Phim Lẻ', slug: 'phim-le'},
  {text: 'Phim Bộ', slug: 'phim-bo'},
  {text: 'Phim Đang Chiếu', slug: 'phim-dang-chieu'},
  {text: 'Hành Động', slug: 'hanh-dong'},
  {text: 'Phiêu Lưu', slug: 'phieu-luu'},
  {text: 'Hoạt Hình', slug: 'hoat-hinh'},
  {text: 'Phim Hài', slug: 'phim-hai'},
  {text: 'Hình Sự', slug: 'hinh-su'},
  {text: 'Tài Liệu', slug: 'tai-lieu'},
  {text: 'Chính Kịch', slug: 'chinh-kich'},
  {text: 'Gia Đình', slug: 'gia-dinh'},
  {text: 'Giả Tưởng', slug: 'gia-tuong'},
  {text: 'Lịch Sử', slug: 'lich-su'},
  {text: 'Kinh Dị', slug: 'kinh-di'},
  {text: 'Nhạc', slug: 'phim-nhac'},
  {text: 'Bí Ẩn', slug: 'bi-an'},
  {text: 'Lãng Mạn', slug: 'lang-man'},
  {text: 'Khoa Học Viễn Tưởng', slug: 'khoa-hoc-vien-tuong'},
  {text: 'Gây Cấn', slug: 'gay-can'},
  {text: 'Chiến Tranh', slug: 'chien-tranh'},
  {text: 'Tâm Lý', slug: 'tam-ly'},
  {text: 'Tình Cảm', slug: 'tinh-cam'},
  {text: 'Cổ Trang', slug: 'co-trang'},
  {text: 'Miền Tây', slug: 'mien-tay'},
  {text: 'Phim 18+', slug: 'phim-18'},
];

export const flagImages: {[key: string]: any} = {
  'au-my': require('../assets/flags/united-states.png'),
  anh: require('../assets/flags/england.png'),
  'trung-quoc': require('../assets/flags/china.png'),
  indonesia: require('../assets/flags/indonesia.png'),
  'viet-nam': require('../assets/flags/vietnam.png'),
  phap: require('../assets/flags/france.png'),
  'hong-kong': require('../assets/flags/hong-kong.png'),
  'han-quoc': require('../assets/flags/south-korea.png'),
  'nhat-ban': require('../assets/flags/japan.png'),
  'thai-lan': require('../assets/flags/thailand.png'),
  'dai-loan': require('../assets/flags/taiwan.png'),
  nga: require('../assets/flags/russia.png'),
  'ha-lan': require('../assets/flags/netherlands.png'),
  philippines: require('../assets/flags/philippines.png'),
  'an-do': require('../assets/flags/india.png'),
  'quoc-gia-khac': require('../assets/flags/red-flag.png'),
};

export const countries = [
  {text: 'Âu Mỹ', slug: 'au-my', imageKey: 'au-my'},
  {text: 'Anh', slug: 'anh', imageKey: 'anh'},
  {text: 'Trung Quốc', slug: 'trung-quoc', imageKey: 'trung-quoc'},
  {text: 'Indonesia', slug: 'indonesia', imageKey: 'indonesia'},
  {text: 'Việt Nam', slug: 'viet-nam', imageKey: 'viet-nam'},
  {text: 'Pháp', slug: 'phap', imageKey: 'phap'},
  {text: 'Hồng Kông', slug: 'hong-kong', imageKey: 'hong-kong'},
  {text: 'Hàn Quốc', slug: 'han-quoc', imageKey: 'han-quoc'},
  {text: 'Nhật Bản', slug: 'nhat-ban', imageKey: 'nhat-ban'},
  {text: 'Thái Lan', slug: 'thai-lan', imageKey: 'thai-lan'},
  {text: 'Đài Loan', slug: 'dai-loan', imageKey: 'dai-loan'},
  {text: 'Nga', slug: 'nga', imageKey: 'nga'},
  {text: 'Hà Lan', slug: 'ha-lan', imageKey: 'ha-lan'},
  {text: 'Philippines', slug: 'philippines', imageKey: 'philippines'},
  {text: 'Ấn Độ', slug: 'an-do', imageKey: 'an-do'},
  {text: 'Quốc gia khác', slug: 'quoc-gia-khac', imageKey: 'quoc-gia-khac'},
];

export const years = [
  '2004',
  '2005',
  '2006',
  '2007',
  '2008',
  '2009',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2022',
  '2023',
  '2024',
];
